
CREATE USER 'alpha' IDENTIFIED BY 'alpha';

GRANT ALL PRIVILEGES ON *.* TO 'alpha' IDENTIFIED BY 'alpha' WITH GRANT OPTION;

SET PASSWORD FOR 'alpha' = PASSWORD('alpha0jet');

INSERT INTO `blog_post` (`id`,`title`,`text`,`created_date`,`published_date`,`author_id`) VALUES (1,'Allez voir vos posts','> et expérimentez un peu avec. Ajoutez 5 ou 6 posts. Ne vous occupez pas du contenu - vous pouvez juste copier du texte de ce tutoriel pour aller plus vite :).\r\n\r\nSur vos 5 posts, faites en sorte qu\'au moins 2 ou 3 posts possèdent une date de publication. Prenez garde à ne pas en donner à tous vos posts car nous allons avoir besoin de ces deux différents cas plus tard.','2018-01-09 12:28:54.000000','2018-01-09 12:29:12.000000',1);
INSERT INTO `blog_post` (`id`,`title`,`text`,`created_date`,`published_date`,`author_id`) VALUES (2,'Si jamais vous voulez en savoir un peu plus','Si jamais vous voulez en savoir un peu plus sur l\'interface d\'administration de Django, vous pouvez lire la documentation qui lui est associée : https://docs.djangoproject.com/fr/1.11/ref/contrib/admin/\r\n\r\nIl est probablement temps d\'aller recharger vos batteries avec un café, un thé ou un truc à grignoter. Vous venez de créer votre modèle Django : vous méritez bien une petite pause !','2018-01-08 06:00:00.000000','2018-01-09 12:30:08.000000',1);
INSERT INTO `blog_post` (`id`,`title`,`text`,`created_date`,`published_date`,`author_id`) VALUES (3,'Afin de vous connecter','Afin de vous connecter, vous allez devoir créer un superuser, c\'est à dire un utilisateur qui contrôlera l\'intégralité du site. Retournez à votre ligne de commande : tapez python manage.py createsuperuser puis appuyez sur entrée. Tapez votre nom d\'utilisateur (en minuscules, sans espace), votre email et votre mot de passe. Vous ne voyez pas le mot de passe que vous êtes en train de taper ? C\'est tout à fait normal, ne vous inquiétez pas ! Tapez simplement votre mot de passe et appuyez sur entrée pour continuer. La sortie que vous allez obtenir doit ressembler à celle-ci. Notez que le nom d\'utilisateur et l\'adresse email doivent correspondre aux informations que vous venez d\'entrer.','2018-01-07 12:30:16.000000','2018-01-07 12:30:54.000000',1);
INSERT INTO `blog_post` (`id`,`title`,`text`,`created_date`,`published_date`,`author_id`) VALUES (4,'Voilà, il est temps de jeter un œil','Voilà, il est temps de jeter un œil à notre modèle Post. N\'oubliez pas d\'exécuter python manage.py runserver dans votre console afin de lancer le serveur web. Dans votre navigateur, entrez l\'adresse http://127.0.0.1:8000/admin/. Si tout va bien, vous verrez une page comme celle-ci:','2018-01-02 12:31:02.000000','2018-01-02 12:31:34.000000',1);
INSERT INTO `blog_post` (`id`,`title`,`text`,`created_date`,`published_date`,`author_id`) VALUES (5,'L\'interface d\'administration de Django','L\'interface d\'administration de Django\r\nPour ajouter, éditer et supprimer les posts que nous venons de modéliser, nous allons utiliser l\'interface d\'administration de Django.','2018-01-04 12:31:47.000000','2018-01-04 12:32:17.000000',1);
